### ISSUE TITLE
Page build failes due to "unknown" Liquid tag `octicon`

### ISSUE THREAD

**Issue by ghost** [nlangnyc/nlangnyc.github.io#3]
Introduced by #1.

The build failure I received via email:

> The page build failed for the `master` branch with the following error:
>
> The tag `octicon` on line 8 in `members.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.
>
> For information on troubleshooting Jekyll see:
>  https://help.github.com/articles/troubleshooting-jekyll-builds

@katychuang: When I set up Jekyll to run locally for #2, I was getting the same error, but I assumed it was a particular to my environment. Were you able to get the `octicon` tag working locally? If so, any idea what we need to do to get it working here?

**Comment by katychuang** [comment]
I'm using Github's very own icon font [octicon](https://octicons.github.com/), and was able to install it locally by adding to the `_config.yml` the gem `jekyll-octicons`

Thought it was supported by Github Pages, but according to [this list of dependencies](https://pages.github.com/versions/), it is not... 🤔

**Comment by ghost** [comment]
That's so weird! This is a strange world with weird dependencies.

It doesn't seem to be causing any harm to the existing site, so we can work this out whenever we're able.

**Comment by katychuang** [comment]
I found this website http://weloveiconfonts.com/ that has icons that can be linked from a cdn, should work without issues! Will make the change soon

**Comment by katychuang** [comment]
Replaced octicons with weloveiconfonts, and merged a pull request with the changes. Let me know if it works!

**Comment by shonfeder** [comment]
The members page is up and working and and I didn't get a build failure message! :D
